server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy temporal de archivos heredados
    location ^~ /wp-content/ {

        proxy_pass https://origin.proyeccionempresarial.com.mx;

        proxy_ssl_verify off;

        proxy_set_header Host origin.proyeccionempresarial.com.mx;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        expires 1y;
        add_header Cache-Control "public";
    }

    # React SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Assets frontend
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|webp|svg|woff2?|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}